### DISCUSSION TITLE
🐳 Docker

### DISCUSSION THREAD

**Discussion by mayukoooo** [mayukoooo/mayukoooo#6] [学び]
入門

**Comment by mayukoooo** [comment]
- apatchのコンテナを作る
    - `--name`：コンテナに名前をつけるオプション
    - `-p`：ポート番号のオプション
    - `httpd`：イメージ名（パラメータ）
    - 下記はapatchのイメージをプルし、コンテナを作成・実行している

```tsx
docker container run --name apatche01 -p 8080:80 -d httpd
```

- アクセス

```tsx
http://localhost:8080/
```

- コンテナを停止する

```tsx
docker container stop apatche01
```

- コンテナを削除する

```tsx
docker container rm apatche01
```

- docker compose
    - コマンドやオプションをファイルにまとめることで、複数コンテナを楽に作成・実行できるソフトウェア。
    - docker desktopにデフォルトで入っている
    - docker composeコマンド
    - YAMLファイル
        - どういうコンテナを作成するかを定義する
        - 構造化データを記述できる記法のこと
        - compose.yaml ~or compose.yml~ 推奨

**Comment by mayukoooo** [comment]
- yamlはインデントに要注意
  - タブは使えない

- docker composeを使ってコンテナの作成実行
  - `docker compose up`：ローカルに対象のイメージが存在しない場合はイメージをプルしてからコンテナを作成・実行する
  - `-d`：コンテナをバックグラウンドで実行させるオプション
    - 付与しないとフォアグランドで実行されるため、コンテナのログが画面上に出力され、PowewShellやターミナル上で続けてコマンドを打つことができなくなる
    - -dオプションを付与して実行した状態を「デタッチモード」と呼ぶ
```typescript
docker compose up -d
```

- 実行中のコンテナを一覧表示
  - statusがupになっていればコンテナが実行されている
```
docker container ls
```

- 全てのコンテナを一覧表示（停止中のコンテナ含む）
```
docker container ls -a
```

<img width="472" alt="スクリーンショット 2024-02-12 16 06 34" src="https://github.com/mayukoooo/mayukoooo/assets/98243891/678733ac-41bc-4afd-979f-81735d8771f8">


- コンテナ起動
  - 複数コンテナがある場合はまとめて起動する
```
docker compose start
```

**Comment by mayukoooo** [comment]
- docker compose ファイルの書き方
```
services: // コンテナのこと
  web: // コンテナ名
    image: httpd:2.4 // 使用するイメージの名前
    ports:
      - "8080:80" // ポート番号
networks: // コンテナで使うネットワークを設定する
  netweb01:
volumes:  // データの保存に関して設定する
  volweb01:
```
<img width="487" alt="スクリーンショット 2024-02-12 17 23 30" src="https://github.com/mayukoooo/mayukoooo/assets/98243891/c246e367-83d9-4cbb-8ace-03645f03f2d2">
